service: nest-serverless-lambda-demo

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /
      - http:
          method: any
          path: /{any+}
